[package]
name = "ractor-supervisor"
version = "0.1.9"
authors = ["https://github.com/simke9445"]
description = "Supervisor module for ractor framework."
documentation = "https://docs.rs/ractor-supervisor"
license = "MIT"
edition = "2021"
keywords = ["actor", "ractor", "supervisor", "ractor-supervisor", "supervision"]
repository = "https://github.com/simke9445/ractor-supervisor"
readme = "./README.md"
homepage = "https://github.com/simke9445/ractor-supervisor"
categories = ["asynchronous"]
rust-version = "1.83.0"

[features]
default = ["async-trait"]
async-trait = ["ractor/async-trait"]

[dependencies]
ractor = "0.15.6"
thiserror = "2.0.11"
if_chain = "1.0.2"
futures-util = "0.3.31"
uuid = { version = "1.12.1", features = ["v4"] }
log = "0.4.20"

[dev-dependencies]
rand = "0.9.0"
serial_test = "3.2.0"
tokio = { version = "1.43.0", features = ["rt-multi-thread"] }
